#!/bin/bash

# Validating for SYFCO
if ! command -v syfco &> /dev/null; then
  echo 'Error: syfco is not installed or not in PATH.' >&2
  exit 1
fi

# Timeout Command
if ! command -v timeout &> /dev/null; then
  echo 'Error: timeout is not installed or not in PATH.' >&2
  exit 1
fi

TLSF_PATH=$1
FIND_DEPENDENCIES_PATH=$2
TIMEOUT_DURATION=${3-40m}

FORMULA=$(syfco $TLSF_PATH -f ltlxba)
INPUTS=$(syfco $TLSF_PATH -ins | awk '{ gsub(/ /,""); print }') # Omit spaces
OUTPUTS=$(syfco $TLSF_PATH -outs | awk '{ gsub(/ /,""); print }')

timeout --signal=HUP ${TIMEOUT_DURATION} ${FIND_DEPENDENCIES_PATH} "${FORMULA}" "${INPUTS}" "${OUTPUTS}"
